# Generated by Django 4.0.3 on 2022-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=100, null=True, verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Progression'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Close'), ('WA', 'Waiting')], default='OP', max_length=5, verbose_name='Status'),
        ),
    ]
