# Generated by Django 3.2.3 on 2022-03-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_project_alter_task_name_alter_task_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Close'), ('WA', 'Waiting')], default='OP', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'étape")),
                ('status', models.CharField(choices=[('FI', 'Finished'), ('BL', 'Blocked'), ('WA', 'Waiting'), ('UN', 'Undefinened')], default='UN', max_length=10, verbose_name='Status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'ordering': ['task', 'status'],
            },
        ),
    ]
