# Generated by Django 3.2.3 on 2022-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_steps_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('FI', 'Termine'), ('BL', 'Bloque'), ('WA', 'En Cours'), ('UN', 'Non Commence')], default='UN', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Ouvert'), ('CL', 'Ferme'), ('WA', 'En Cours')], default='OP', max_length=10, verbose_name='Status'),
        ),
    ]
