# Generated by Django 4.0.3 on 2022-03-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_step_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['task', 'id']},
        ),
    ]
