# Generated by Django 4.0.3 on 2022-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_description_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('Terminé', 'Finished'), ('Bloqué', 'Blocked'), ('En cours', 'In Progress'), ('Créé', 'Undefined')], default='Créé', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Projet'),
        ),
    ]
