# Generated by Django 4.0.3 on 2022-03-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
