# Generated by Django 3.2.3 on 2022-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='formation',
            name='picture',
            field=models.CharField(default='media/formations/default.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.CharField(default='media/projects/default.png', max_length=100),
        ),
    ]
