# Generated by Django 3.2.3 on 2022-03-11 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_formation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Compétence')),
                ('progress', models.IntegerField(default=0)),
                ('color', models.CharField(default='#06D7A0', max_length=7, verbose_name='Couleur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
