# Generated by Django 4.0.3 on 2022-03-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220311_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='progress',
            new_name='value',
        ),
    ]
