# Generated by Django 3.2.3 on 2022-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220307_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'name', 'status']},
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('Terminé', 'Finished'), ('Bloqué', 'Blocked'), ('En cours', 'In Progress'), ('Non commencé', 'Undefined')], default='Non commencé', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'Open'), ('Fermé', 'Closed'), ('En cours', 'In Progress')], default='Ouvert', max_length=20, verbose_name='Status'),
        ),
    ]
