# Generated by Django 3.2.3 on 2022-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220307_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Projet'),
        ),
    ]
