# Generated by Django 4.0.3 on 2022-03-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'id', 'status']},
        ),
    ]
